### ISSUE TITLE
Use specified network interface with nmap

### ISSUE THREAD

**Issue by Dbof** [secgroundzero/warberry#49]
Nmap should use the same network interface the script uses. Right now, when I connect the Pi via LAN cable, nmap still tries to use wlan0 for scanning. You can specify an interface with the **-e** option of nmap, which should be used in the warberry scripts.

My current problem is that Nmap does not work well with the integrated WiFi on the Rpi3, but since the Pi is connected directly, it should use eth0.

**Comment by secgroundzero** [comment]
i am releasing an update for this.

nice catch

**Comment by secgroundzero** [comment]
The warberry first step is to find out the scope of testing. So lets say it found some IPs on 192.168.2.x) only those will be included in the test.

if your eth0 has an IP 192.168.2.5 and your wlan0 has 192.168.2.5 (if you are using both)  then it will use eth0 by default.

a problem will arise only when  the eth0 and wlan0 share the same IP ranges

since you are specifying an interface or default to eth0 during setup then you should be fine and nmap will scan those.

**Comment by Dbof** [comment]
I have eth0 and wlan0 on the same subnet (192.168.2.*), but still, if I define the interface for warberry (with -I), it should also use the same interface for nmap. Problem is: Nmap _sometimes_ uses wlan0 by default, which fails on the Rpi3. 

By the way, [your commit](https://github.com/secgroundzero/warberry/commit/3422e9243bdbed36d4d6a5f9cba1371c88d80dde) was incomplete, since you forgot to change the function definitions of *_port_scanner() in the corresponding files. Consequently, it throws an exception...

**Comment by secgroundzero** [comment]
that was the leftovers from trying to find a solution for your issue

i pushed an update for that

regarding the interface definition you will need to wait a bit for the next release. if you can make some suggestions for the code changes that would save time.

thank you
